"""add original info at content and delete unique constraint in proposal

Revision ID: 0ba72483ddee
Revises: 7194ba23382f
Create Date: 2026-01-19 05:24:58.021770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ba72483ddee'
down_revision: Union[str, Sequence[str], None] = '7194ba23382f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_assumption_proposals_assumption_user'), 'assumption_proposals', type_='unique')
    op.add_column('assumptions', sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('assumptions', sa.Column('is_modified', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('assumptions', sa.Column('original_content', sa.Text(), nullable=True))
    op.drop_constraint(op.f('uq_conclusion_proposals_criterion_user'), 'conclusion_proposals', type_='unique')
    op.drop_constraint(op.f('uq_criteria_proposals_criteria_user'), 'criteria_proposals', type_='unique')
    op.add_column('criterion', sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('criterion', sa.Column('is_modified', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('criterion', sa.Column('original_content', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('criterion', 'original_content')
    op.drop_column('criterion', 'is_modified')
    op.drop_column('criterion', 'is_deleted')
    op.create_unique_constraint(op.f('uq_criteria_proposals_criteria_user'), 'criteria_proposals', ['criteria_id', 'created_by'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('uq_conclusion_proposals_criterion_user'), 'conclusion_proposals', ['criterion_id', 'created_by'], postgresql_nulls_not_distinct=False)
    op.drop_column('assumptions', 'original_content')
    op.drop_column('assumptions', 'is_modified')
    op.drop_column('assumptions', 'is_deleted')
    op.create_unique_constraint(op.f('uq_assumption_proposals_assumption_user'), 'assumption_proposals', ['assumption_id', 'created_by'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
