"""add sse to outbox table

Revision ID: c686ecae9db2
Revises: 0f932fe1bb0b
Create Date: 2026-01-21 04:01:32.389131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c686ecae9db2'
down_revision: Union[str, Sequence[str], None] = '0f932fe1bb0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # 1. nullable=True로 컬럼 추가
    op.add_column('outbox_events', sa.Column('target_event_id', sa.UUID(), nullable=True))
    
    # 2. 기존 데이터 마이그레이션: payload->>'event_id'에서 추출하여 채움
    op.execute("""
        UPDATE outbox_events 
        SET target_event_id = (payload->>'event_id')::uuid 
        WHERE payload->>'event_id' IS NOT NULL
    """)
    
    # 3. nullable=False로 변경
    op.alter_column('outbox_events', 'target_event_id', nullable=False)
    
    # 4. 인덱스 추가
    op.create_index('idx_outbox_target_event_id', 'outbox_events', ['target_event_id', 'id'], unique=False)
    op.create_index(op.f('ix_outbox_events_target_event_id'), 'outbox_events', ['target_event_id'], unique=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_outbox_events_target_event_id'), table_name='outbox_events')
    op.drop_index('idx_outbox_target_event_id', table_name='outbox_events')
    op.drop_column('outbox_events', 'target_event_id')
    # ### end Alembic commands ###
