#!/usr/bin/env bash
set -euo pipefail

# .env 로드
if [ -f .env ]; then
  export $(grep -v '^#' .env | xargs)
fi

: "${POSTGRES_DB:?POSTGRES_DB is required}"
: "${POSTGRES_USER:?POSTGRES_USER is required}"
: "${POSTGRES_PASSWORD:?POSTGRES_PASSWORD is required}"
: "${APP_RUNTIME_PASSWORD:?APP_RUNTIME_PASSWORD is required}"

APP_RUNTIME_PASSWORD_SQL=${APP_RUNTIME_PASSWORD//\'/\'\'}

DB_CONT="${DB_CONT:-db}"
OWNER_ROLE="${POSTGRES_USER}"
RUNTIME_ROLE="${RUNTIME_ROLE:-app_runtime}"
SCHEMA_NAME="${SCHEMA_NAME:-public}"

echo "[db_bootstrap] owner=${OWNER_ROLE}, runtime=${RUNTIME_ROLE}, db=${POSTGRES_DB}"

docker compose exec "${DB_CONT}" sh -lc "
psql -v ON_ERROR_STOP=1 -U \"${OWNER_ROLE}\" -d \"${POSTGRES_DB}\" <<'SQL'
DO \$\$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = '${RUNTIME_ROLE}') THEN
    CREATE ROLE ${RUNTIME_ROLE} LOGIN PASSWORD '${APP_RUNTIME_PASSWORD_SQL}';
  ELSE
    ALTER ROLE ${RUNTIME_ROLE} WITH PASSWORD '${APP_RUNTIME_PASSWORD_SQL}';
  END IF;
END
\$\$;

GRANT CONNECT ON DATABASE ${POSTGRES_DB} TO ${RUNTIME_ROLE};
GRANT USAGE ON SCHEMA ${SCHEMA_NAME} TO ${RUNTIME_ROLE};

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA ${SCHEMA_NAME} TO ${RUNTIME_ROLE};
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA ${SCHEMA_NAME} TO ${RUNTIME_ROLE};

ALTER DEFAULT PRIVILEGES IN SCHEMA ${SCHEMA_NAME}
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO ${RUNTIME_ROLE};

ALTER DEFAULT PRIVILEGES IN SCHEMA ${SCHEMA_NAME}
  GRANT USAGE, SELECT ON SEQUENCES TO ${RUNTIME_ROLE};
SQL
"
